### ISSUE TITLE
LowPower.deepSleep doesnt work

### ISSUE THREAD

**Issue by Narceen** [stm32duino/STM32LowPower#10]
Hello,

i use an Custom Stm32L432KC Board but if i use LowPower.deepSleep in my Code in Arduino Windows tell me the USB Device got some Error -> Invalid Device Description.

If i use LowPower.sleep, it wont work at all, Serial.print occour infinity no delay at all.

So maybe u can help me and tell what i do wrong?

**Comment by fpistm** [comment]
Hi,

I guess you probably need to handle properly USB disconnection or config.
Library does not manages peripherals configurations so before enter in the LP mode you have to manage them.
You can also write your own `SystemClock_ConfigFromStop` which by default call the `SystemClock_Config`.

**Comment by Narceen** [comment]
Hi, thx for the replay. I just fixed the usb error with new driver update.
Can u give me a hint how to configurate peripherals for LP Mode?
Thx in advantage

**Comment by fpistm** [comment]
OP issue solved.
For the hint, please use the forum for primary support.
