### ISSUE TITLE
SerialDeepSleep not working with user defined Harware Serial ?

### ISSUE THREAD

**Issue by Yannick-Marietti** [stm32duino/STM32LowPower#107]
Hello
It seems example SerialDeepSleep.ino does not work with an hardware serial diffrent form the "Serial" default.
For example, on my computer, the attached (picture) code does not run beyond row 33.

![Capture d’écran 2024-02-17 093553](https://github.com/stm32duino/STM32LowPower/assets/38190699/497e5e37-2678-41aa-a9fc-5e810681bed4)

Best regards

Yannick

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Arduino IDE version: 2.3.1
 - STM32 core version: 2.7.1
 - Library version: STM32duino Low Power 1.2.5
 - Upload method: Mass storage

**Hardware (please complete the following information):**
 - Board Name: NUCLEO L476RG
 

**Additional context**

**Comment by fpistm** [comment]
The uart have to be low power compliant. Ex lpuart.

**Comment by fpistm** [comment]
Extract from L476 ref man
![Screenshot_20240217_132933_Drive](https://github.com/stm32duino/STM32LowPower/assets/20641798/0277b00c-8ddc-4a18-a02f-a2bea3291b6f)

**Comment by fpistm** [comment]
Will chech deeply next week

**Comment by fpistm** [comment]
Hi @Yannick-Marietti 
I've tested and it works as expected using UART4 defined manually.
![image](https://github.com/stm32duino/STM32LowPower/assets/20641798/64ca2e72-5965-4355-b6fe-49cfff40e98d)

Just for information about deepsleep and wakeup from serial feature.
If the Serial is a LPUART then mcu will go in stop 2 mode, if not the stop mode 1 is used to be able to wake up.
See datasheet:
![image](https://github.com/stm32duino/STM32LowPower/assets/20641798/681c3363-7fb9-48d0-989f-c84251d5dc88)
With default Serial of the Nucleo L476RG, Serial is USART2 so STOP1 mode is used same if we use UART4.
