### ISSUE TITLE
library cant upload to stm32f103c8

### ISSUE THREAD

**Issue by Naveenkato** [stm32duino/STM32LowPower#11]
when i upload this library to stm32f103c8t6 board,I stuck with this error"#error "PWR configuration is missing. Check flag HAL_PWR_MODULE_ENABLED in variants/board_name/stm32yzxx_hal_conf.h"

**Comment by fpistm** [comment]
Hi  @Naveenkato 
This library is for this core:
https://github.com/stm32duino/Arduino_Core_STM32

I guess you do not use this core but this one: https://github.com/rogerclarkmelbourne/Arduino_STM32

That's why you get this error as this library is not compatible with it.

**Comment by Naveenkato** [comment]
Thank you.I solved this problem.

**Comment by jos3c0** [comment]
@Naveenkato, how do you resolve the problem? Can you share us that info, i have the same issue

**Comment by fpistm** [comment]
@jos3c0 
As I explained you probably do not use this core:
https://github.com/stm32duino/Arduino_Core_STM32
but this one:
https://github.com/rogerclarkmelbourne/Arduino_STM32
So, this library is not compatible.

**Comment by jos3c0** [comment]
@fpistm 
I am a little confused. I was checking on the issue appearing on
"controller consumes high power during sleep mode #12" and it seems @Naveenkato is using the library with the blue pill(sm32f103c8t6). I want to understand how he managed to do it.

**Comment by fpistm** [comment]
I guess he has moved to this core https://github.com/stm32duino/Arduino_Core_STM32
