### ISSUE TITLE
Serial wakeup with time

### ISSUE THREAD

**Issue by geologic** [stm32duino/STM32LowPower#111]
Hi

I have a project on a custom STM32L0 board where i want to deepsleep and be able to wake up by serial. 
I uploaded the SerialDeepSleep example  and it works as expected.

Since i want a led hartbeat i just changed this line to

`LowPower.deepSleep(3000);`

I was expecting the same behavior as before, but now i see every 3 seconds:

```
Start deep sleep wakeup from Serial
1 wake up

2 wake up

3 wake up

4 wake up

5 wake up

```
So, it seems with timed deepsleep, when timeout occurs, the SerialWakeup() is called even i don´t send anything on serial.
Is this normal or a bug?

Thanks

**Comment by fpistm** [comment]
This is normal, you ask to wake up each 3 second. So the sketch do the print each wakeup. The serial callback is called unconditionally,  up to you to check the wakeup source. Example check if Serial data is available before incrementing the counter.
Anyway couter value is correct as a wakup is occured.

Please next time avoid t open an issue as stated when you click "New issue":
![image](https://github.com/stm32duino/STM32LowPower/assets/20641798/941dc80e-0d0a-40ca-887e-b1035a709926)
