### ISSUE TITLE
deepSleep() incompatibility with STM32duino USB support

### ISSUE THREAD

**Issue by rayozzie** [stm32duino/STM32LowPower#114]
My sketch is using Arduino IDE 2.3.3 with STM32duino version 2.8.1 with a Blues Cygnet (STM32L433) mcu which has an LSE.

As many do, I always initialize my sketch with: 

```
#define debug Serial
    debug.begin(115200);
    bool serialInitialized = false;
    if (waitForSerialInit) {
	uint64_t expiresMs = millis64() + 2500;
        while (millis64() < expiresMs) {
            if (debug) {
                serialInitialized = true;
                break;
            }
        }
    }
```

I then initialize the low power package with
```
    rtc.setClockSource(STM32RTC::LSE_CLOCK);
    rtc.setBinaryMode(STM32RTC::MODE_BCD);
    rtc.begin(true);
    LowPower.begin();
```

In my loop, when I'd like to go into deep sleep mode I do
```
    LowPower.deepSleep(sleepMs);
```

This works wonderfully, and sleeps for sleepMs when the above "serialInitialized" returns 'true'.

The LowPower.deepSleep() call returns in just one or two milliseconds, regardless of sleepMs, when the above "serialInitialized" returns 'false'.

The core problem turns out to be the fact that, when using Arduino's 
```USB Support: CDC (generic 'Serial' supersede U(S)ART)```
...IF AND ONLY IF the USB is unplugged at the time of setup().  And if indeed the USB is unplugged at the time of setup(), (as helpfully indicated by serialInitialized being false) deepSleep() will fail.

If the USB is plugged in during setup(), OR if USB Support is set to 'None', serialInitialized returns 'true' and deepSleep() works fine.

The workaround in my device (which happens to have a screen) is to use that serialInitialized flag to warn the user to rebuild the sketch without USB support, however it would be best if deepSleep() were enhanced so that it does not immediately wake if USB support is configured but unplugged.

Thank you for a great library and for your consideration.

**Comment by fpistm** [comment]
Hi @rayozzie 
Please, could you share a full sketch?

**Comment by rayozzie** [comment]
Here's the full sketch, Frederic.

When you have the USB plugged in, the LED on the board is a steady 1 second blink of the LED.  When you unplug the USB, the LED is on continuously because the processor is not sleeping.

Note that my sketch settings are:
![Untitled](https://github.com/user-attachments/assets/f22a7fc5-765a-4e00-851a-bf80ba672062)


`
#include <STM32LowPower.h>

void setup() {
    pinMode(LED_BUILTIN, OUTPUT);
    Serial.begin(115200);
    LowPower.begin();
}

void loop() {
    digitalWrite(LED_BUILTIN, HIGH);
    delay(1000);
    digitalWrite(LED_BUILTIN, LOW);
    LowPower.deepSleep(1000);
    Serial.begin(115200);
}

`

**Comment by fpistm** [comment]
Thanks @rayozzie 
Did you test to end the Serial:
```patch
void loop() {
    digitalWrite(LED_BUILTIN, HIGH);
    delay(1000);
    digitalWrite(LED_BUILTIN, LOW);
+   Serial.end();
    LowPower.deepSleep(1000);
    Serial.begin(115200);  // re-initialize serial when coming out of sleep
}
```

**Comment by zfields** [comment]
I do that now, but it was not obvious to me initially.

I'm just offering my experience as feedback.

**Comment by fpistm** [comment]
> I'm just offering my experience as feedback.

Always appreciate. This is a community project any feedback/contributions are welcome.
In a general way, if you don't need a "feature" it is always good practice to disable it to save ram/rom consumption and potentially power.
