### ISSUE TITLE
The STM32G070 cannot be configured with more than 5 external awakenings

### ISSUE THREAD

**Issue by ShiPC123** [stm32duino/STM32LowPower#115]
Hello, I am using the chip STM32G070K8T6 and the compiler version is 2.7.1. If I configure 6 external keys to wake up the chip, one of them does not work
this is my code

#include <STM32LowPower.h>

STM32RTC &rtc = STM32RTC::getInstance(); // 开启RTC

#define KEY1 PA3
#define KEY2 PA8
#define KEY3 PB6
#define KEY4 PA15
#define KEY5 PB7
#define KEY6 PB3

#define LED PA2

void setup() {
  delay(2000);
  pinMode(KEY1, INPUT);
  pinMode(KEY2, INPUT);
  pinMode(KEY3, INPUT);
  pinMode(KEY4, INPUT);
  pinMode(KEY5, INPUT);
  pinMode(KEY6, INPUT);

  pinMode(LED, OUTPUT);
  rtc.setClockSource(STM32RTC::LSI_CLOCK);
  rtc.begin();
  LowPower.begin();
  LowPower.attachInterruptWakeup(KEY2, KEY2_Wakeup, FALLING, DEEP_SLEEP_MODE);
  LowPower.attachInterruptWakeup(KEY1, KEY1_Wakeup, FALLING, DEEP_SLEEP_MODE);

  LowPower.attachInterruptWakeup(KEY3, KEY3_Wakeup, FALLING, DEEP_SLEEP_MODE);
  LowPower.attachInterruptWakeup(KEY4, KEY4_Wakeup, FALLING, DEEP_SLEEP_MODE);
  LowPower.attachInterruptWakeup(KEY5, KEY5_Wakeup, FALLING, DEEP_SLEEP_MODE);
  LowPower.attachInterruptWakeup(KEY6, KEY6_Wakeup, FALLING, DEEP_SLEEP_MODE);

}

void loop() {
  for (int i = 0 ; i < 5; i++) {
    digitalWrite(LED, LOW);
    delay(100);
    digitalWrite(LED, HIGH);
    delay(100);
  }
  LowPower.deepSleep();

}

void KEY1_Wakeup() {

}

void KEY2_Wakeup() {
  
}
void KEY3_Wakeup() {
  
}
void KEY4_Wakeup() {
 
}
void KEY5_Wakeup() {
 
}
void KEY6_Wakeup() {
 
}

**Comment by fpistm** [comment]
Hi @ShiPC123 
This is not a bug. PA3 and PB3 have the same interrupt vector. Only GPIO pin number is relevant. No GPIO port.
