### ISSUE TITLE
Strange adc behaviour after deepSleep

### ISSUE THREAD

**Issue by volvofixthis** [stm32duino/STM32LowPower#24]
In my setup i need to measure voltage between 0v and 5v. I used resistive devider with two 10kOm resistors. And used analogRead to measure analog input. After waking up recived value is around 10% lower then before deepSleep. I am using board blue pill with this chip CKS32F 103C8T6 NK1M5 1845 E. I tried different variants to initialize ADC again after sleep, but without luck. Now i do software reset after waking up, but i want to do it properly.

**Comment by fpistm** [comment]
Hi @volvofixthis 
I've tested with a BP and a STM32F103C8 without any issue. The analog read after a deep sleep are correct.
This library supports only official STM32 MCU.
