### ISSUE TITLE
Low power Arduino Library for STM32L151

### ISSUE THREAD

**Issue by mamanbudiman** [stm32duino/STM32LowPower#26]
I have tested this lowpower arduino to the RAK811 LoRa module.
Using this example in this github, the deepSleep/shutdown current is about 3.5miliAmp,
while using RAK811 firmware, the deepSleep current can be about 12 microAmp.

Do you have any explanation for the difference ?

Regards,

**Comment by fpistm** [comment]
> Do you have any explanation for the difference ?

Yes, I guess the RAK811 fw do some extra configuration. This library only set the MCU is the required mode but some extrq config should/could be done: all pins in analog input mode, shutdown the radio, ...
