### ISSUE TITLE
Multiple External Interrupt Not working in Deep Sleep Mode

### ISSUE THREAD

**Issue by srjtmitra5** [stm32duino/STM32LowPower#35]
In Low Power Deep Sleep mode  in setup multiple external interrupt pins declared. But only one ISR is responding while others are not working. If I pick only one at a time and comment out the rest then it is working. I want to use multiple external interrupts as source of wake-up. Please help!

**Comment by fpistm** [comment]
Hi @srjtmitra5 
Could you be more precise about your setup and code ?
Which board? sketch? core version and library?
Thanks in advance.

**Comment by srjtmitra5** [comment]
Hello!,
I am using STM32F103RBT6,
Library : https://github.com/stm32duino/STM32LowPower
I am using this example: https://github.com/stm32duino/STM32LowPower/tree/master/examples/ExternalWakeup
It is working great with a single interrupt but failing for multiple.
Thanks for your comment!

**Comment by srjtmitra5** [comment]
My apologies. I forgot to mention that in the example we have LowPower.sleep() but I replaced it with LowPower.deepSleep(). Is that a reason?

**Comment by fpistm** [comment]
Which pins did you try?

**Comment by srjtmitra5** [comment]
I think I have done some mistake in the hardware. I am still checking. For now I am closing this issue unless I am absolutely sure
