### ISSUE TITLE
WKUP pin for shutdown mode

### ISSUE THREAD

**Issue by msadeghz** [stm32duino/STM32LowPower#38]
Hi friends,
I want to wake up the micro-controller from shutdown mode using WKUP pin (PA0). is there anyway to do it in this repository approach?

**Comment by fpistm** [comment]
Hi @msadeghz ,
yes, use the `attachInterruptWakeup`, usually PA0 is `SYS_WKUP0`:

```C++
  // Configure low power
  LowPower.begin();

  LowPower.attachInterruptWakeup(SYS_WKUP0, your, RISING);
  ...
  LowPower.shutdown();
```

**Comment by msadeghz** [comment]
OK, got it.
thank you
