### ISSUE TITLE
Is Wire.h required?

### ISSUE THREAD

**Issue by PeeJay** [stm32duino/STM32LowPower#39]
I noticed a reference to wire.h at STM32LowPower.h:52 - Is this required? Removing it makes less code build, but the final binary seems to stay the same size.

**Comment by fpistm** [comment]
Hi @PeeJay 

probably not needed as it is for I2C. Probably added because it is planned to support I2C wakeup.

For the binary size this is normal as the linker remove all unneeded reference.
