### ISSUE TITLE
attachInterruptWakeup pin works only for PA0 on bluepill

### ISSUE THREAD

**Issue by evansgl** [stm32duino/STM32LowPower#41]
Seems that attachInterruptWakeup pin works only for PA0 pin on BluePill.
I have tried other pins but I can only trigger the wake up of the board from PA0 (even if I set other pins e.g PA1 at below code)
Do I miss something here?

```
const int BUTTON_PIN = PA1;
LowPower.attachInterruptWakeup(BUTTON_PIN, repetitionsIncrease, RISING);

```

**Comment by fpistm** [comment]
Hi @evansgl 
STM32F103C8 has only one system wakeup pin: PA0.
https://github.com/stm32duino/Arduino_Core_STM32/blob/1faf0a0ead7b6ae07258d706c1e9052de0be6cf0/variants/PILL_F103XX/PinNamesVar.h#L3

You can't use another pin to wake up the board.
