### ISSUE TITLE
Got compilation errors

### ISSUE THREAD

**Issue by pankleks** [stm32duino/STM32LowPower#42]
Hello,

I've been trying to use this library with Blue Pill board.

After adding dependency to STM32RTC + Wire, I got following (adding platformio config):

![image](https://user-images.githubusercontent.com/14176066/101242841-5d4e4080-36fc-11eb-80d2-c4cedf77e0c1.png)

Thank you in advance for help!

**Comment by pankleks** [comment]
when I donwgraded to 1.0.3 all is compiling fine.

but when you install library by platform IO it is installing by default 1.1.0 version.

**Comment by fpistm** [comment]
Hi @pankleks 
As explained here:
https://github.com/stm32duino/STM32LowPower/issues/34#issuecomment-707802604

The 1.1.0 is not yet released as it depends on the STM32 core.
