### ISSUE TITLE
Include guard prevents low_power.h from being included and thus build fails

### ISSUE THREAD

**Issue by LaBus3** [stm32duino/STM32LowPower#47]
```
#if defined(STM32_CORE_VERSION) && (STM32_CORE_VERSION  > 0x01090000)
  #include "low_power.h"
#endif
```

The library uses methods from low_power.h. 
Latest stable core version is 1.9.0 but include guard states STM32_CORE_VERSION  > 0x01090000. No such limitation is noted in README.
Regards.

**Comment by fpistm** [comment]
The README will be updated when the new release will be done.
There is no issue with this guard it allows to keep a backward compatibility on some case.
The low_power.* have been moved from the core to the lib.
