### ISSUE TITLE
Minimun achived current is 1.4 mA

### ISSUE THREAD

**Issue by mateuscelio** [stm32duino/STM32LowPower#62]
I am trying to use this library but the minimum current that I am getting with shutdown mode is 1.4 mA. The same result was observed in Platform.IO and Arduino IDE.

I flash the program using serial mode.

The board is a blackpill with stm32f103c8t6

```
#include <low_power.h>
#include <STM32LowPower.h>

void setup() {
  LowPower.begin();
  LowPower.shutdown(15000);

}

void loop() {

}
```

**Comment by fpistm** [comment]
Hi @mateuscelio 
I've measured the IDD of a Nucleo F103RB using your sketch and I have 4µA.
As stated by @yetoo it is linked to your board.
Other topic on this subject:
https://www.stm32duino.com/viewtopic.php?p=8838#p8838

**Comment by mateuscelio** [comment]
Thanks @yetoo  and @fpistm, I found the problem and it was the power LED. Removing it, the consuming current now is 70uA in shutdown mode.
