### ISSUE TITLE
deepSleep takes effect after power down

### ISSUE THREAD

**Issue by xvedra** [stm32duino/STM32LowPower#89]
Hi,
I am working with deepSleep in a BluePill and I have notice that it takes effect only after a power down. Procedure:
1) BluePill power on from St-Link.
2) Clear flash memory
3) Program deepSleep example and does not take effect.
4) Power down: Switch off and switch on St-link . After that it takes effect.
Thank you

**Comment by fpistm** [comment]
Hi @xvedra 
Howyou flash it?

**Comment by xvedra** [comment]
Hi @fpistm,
IDE 1.8.19 Under Windows 10 pro
upload method: SWD (ST-LINK)
Target: BluePill F103C8
What happen if you manually reset it (not power down)? The same...

After read this:
https://github.com/stm32duino/STM32LowPower/issues/36

Works fine adding HAL_SuspendTick();  before LowPower.deepSleep(); 

Thank you!

**Comment by fpistm** [comment]
You used LSE?

**Comment by xvedra** [comment]
BluePill board has LSE but I have used the simplest example without LSE:

void setup()
 {
pinMode(LED_BUILTIN, OUTPUT);
LowPower.begin();
}

void loop() 
{
  digitalWrite(LED_BUILTIN, HIGH);
  HAL_SuspendTick(); //added
  LowPower.deepSleep(2000);
  HAL_ResumeTick(); //added
  //LowPower.sleep();
  digitalWrite(LED_BUILTIN, LOW);
  HAL_SuspendTick();  //added
  LowPower.deepSleep(2000);
  HAL_ResumeTick(); //added
  //LowPower.sleep();
}

There was no problem using with LowPower.sleep()

**Comment by fpistm** [comment]
Is it a legacy chip? Not a clone?

**Comment by fpistm** [comment]
I've tested on my side and have no issue.
Ensure to have latest library version, latest core version and  latest STM32CubeProgrammer as you used SWD.
I've tested with different setup, USB enabled or not,... all works.
Moreover it seems strange using `HAL_SuspendTick` allows to work as the `deepSleep `disable the irq before entering in low power.

**Comment by xvedra** [comment]
Is it a legacy chip? Not a clone?
_My BluePill is from Aliexpress. I don't know if it's a clone. I have a custom board with a legacy STM32F108CB with the same result._
_Ensure to have latest library version, latest core version and latest STM32CubeProgrammer as you used SWD..
Latest versions_ 
Moreover it seems strange using HAL_SuspendTick allows to work as the deepSleep disable the irq before entering in low power.
Yes, but only in

**Comment by fpistm** [comment]
I've made the same test than you and it works.
I've tested with several BluePill, MapleMini and STM32F103ZE and all works. 
So I have no more clue except if it is a clone and in that case could explain why it does not work. You could try to ask on the forum maybe someone already met this issue.
I close it as it works.
