### ISSUE TITLE
Support for Arduino_STM32

### ISSUE THREAD

**Issue by LucasFeliciano21** [stm32duino/STM32LowPower#9]
Hi guys, I'm currently using the Arduino_STM32 from [here](https://github.com/rogerclarkmelbourne/Arduino_STM32) and i couldn't find a way to run this version on there. There is some possibility to run the same code using that core? thanks

**Comment by fpistm** [comment]
Hi @LucasFeliciano21 
this library is designed for this core https://github.com/stm32duino/Arduino_Core_STM32
and used CMSIS definitions, STM32RTC library and STM32 HAL.
To run it to other core this will required to fully implement all those parts including this part of the core: https://github.com/stm32duino/Arduino_Core_STM32/blob/master/cores/arduino/stm32/low_power.c

You can refer to this post to use low power for this core: 
http://www.stm32duino.com/viewtopic.php?f=3&t=658
